from datetime import datetime

from entsoe_api.enums import DocumentType, DomainType, ProcessType

RESOURCES_CONFIG = [
    {
        "path": "xml_resources/wind_and_solar_forecast_no2_2025.xml",
        "params": dict(
            start_date=datetime(2025, 1, 1),
            end_date=datetime(2025, 12, 31),
            document_type=DocumentType.WIND_AND_SOLAR_FORECAST,
            process_type=ProcessType.DAY_AHEAD,
            in_domain=DomainType.NO2,
        ),
        "expected_columns": ["SOLAR_GENERATION", "WIND_OFFSHORE_GENERATION", "WIND_ONSHORE_GENERATION"],
        "expected_start_timestamp": datetime(2025, 1, 1, 0, 0),
        "expected_end_timestamp": datetime(2025, 12, 31, 23, 0),
        "excepted_errors": None,
    },
    {
        "path": "xml_resources/wind_and_solar_forecast_de_lu_2022-01.xml",
        "params": dict(
            start_date=datetime(2022, 1, 1),
            end_date=datetime(2022, 1, 31),
            document_type=DocumentType.WIND_AND_SOLAR_FORECAST,
            process_type=ProcessType.DAY_AHEAD,
            in_domain=DomainType.DE_LU,
        ),
        "expected_columns": ["SOLAR_GENERATION", "WIND_OFFSHORE_GENERATION", "WIND_ONSHORE_GENERATION"],
        "expected_start_timestamp": datetime(2022, 1, 1, 0, 0),
        "expected_end_timestamp": datetime(2022, 1, 31, 23, 0),
        "excepted_errors": None,
    },
    {
        "path": "xml_resources/actual_generation_per_type_pl_2026-04-04.xml",
        "params": dict(
            start_date=datetime(2026, 4, 4),
            end_date=datetime(2026, 4, 5),
            document_type=DocumentType.ACTUAL_GENERATION_PER_TYPE,
            process_type=ProcessType.REALISED,
            in_domain=DomainType.PL,
        ),
        "expected_columns": [
            "BIOMASS_GENERATION",
            "FOSSIL_BROWN_COAL_LIGNITE_GENERATION",
            "FOSSIL_COAL_DERIVED_GAS_GENERATION",
            "FOSSIL_GAS_GENERATION",
            "FOSSIL_HARD_COAL_GENERATION",
            "FOSSIL_OIL_GENERATION",
            "HYDRO_PUMPED_STORAGE_GENERATION",
            "HYDRO_PUMPED_STORAGE_CONSUMPTION",
            "HYDRO_RUN_OF_RIVER_POUNDAGE_GENERATION",
            "HYDRO_WATER_RESERVOIR_GENERATION",
            "OTHER_GENERATION",
            "OTHER_RENEWABLE_GENERATION",
            "SOLAR_GENERATION",
            "WIND_ONSHORE_GENERATION",
        ],
        "expected_rows": {
            "BIOMASS_GENERATION": 96,
            "FOSSIL_BROWN_COAL_LIGNITE_GENERATION": 96,
            "FOSSIL_COAL_DERIVED_GAS_GENERATION": 96,
            "FOSSIL_GAS_GENERATION": 96,
            "FOSSIL_HARD_COAL_GENERATION": 96,
            "FOSSIL_OIL_GENERATION": 96,
            "HYDRO_PUMPED_STORAGE_GENERATION": 21,  # Only 21 values for this type
            "HYDRO_PUMPED_STORAGE_CONSUMPTION": 86,  # Only 21 values for this type
            "HYDRO_RUN_OF_RIVER_POUNDAGE_GENERATION": 86,  # Only 86 values for this type
            "HYDRO_WATER_RESERVOIR_GENERATION": 68,  # Only 68 values for this type
            "OTHER_GENERATION": 96,
            "OTHER_RENEWABLE_GENERATION": 96,
            "SOLAR_GENERATION": 57,  # Only 57 values for this type
            "WIND_ONSHORE_GENERATION": 96,
        },
        "expected_start_timestamp": datetime(2026, 4, 4, 0, 0),
        "expected_end_timestamp": datetime(2026, 4, 5, 0, 0),
        "excepted_errors": None,
    },
    {
        "path": "xml_resources/price_document_fr_2016-05-13.xml",
        "params": dict(
            start_date=datetime(2016, 5, 12, 22),
            end_date=datetime(2016, 5, 13, 22),
            document_type=DocumentType.PRICE_DOCUMENT,
            process_type=ProcessType.REALISED,
            in_domain=DomainType.FR,
        ),
        "expected_rows": {"PRICE": 24},
        "expected_columns": ["PRICE"],
        "expected_start_timestamp": datetime(2016, 5, 12, 22, 0),
        "expected_end_timestamp": datetime(2016, 5, 13, 22, 0),
        "excepted_errors": None,
    },
    {
        "path": "xml_resources/system_total_load_es_2024-08-19.xml",
        "params": dict(
            start_date=datetime(2024, 8, 18, 22),
            end_date=datetime(2024, 8, 19, 22),
            document_type=DocumentType.SYSTEM_TOTAL_LOAD,
            process_type=ProcessType.DAY_AHEAD,
            in_domain=DomainType.ES,
        ),
        "expected_rows": {"TOTAL_LOAD": 96},
        "expected_columns": ["TOTAL_LOAD"],
        "expected_start_timestamp": datetime(2024, 8, 18, 22, 0),
        "expected_end_timestamp": datetime(2024, 8, 19, 22, 0),
        "excepted_errors": None,
    },
    {
        "path": "xml_resources/aggregated_energy_es-fr_2024-08-19.xml",
        "params": dict(
            start_date=datetime(2024, 8, 18, 22),
            end_date=datetime(2024, 8, 19, 22),
            document_type=DocumentType.AGGREGATED_ENERGY_DATA_REPORT,
            process_type=ProcessType.REALISED,
            in_domain=DomainType.ES,
            out_domain=DomainType.FR,
        ),
        "expected_rows": {"FLOW_FR_TO_ES": 93},
        "expected_columns": ["FLOW_FR_TO_ES"],
        "expected_start_timestamp": datetime(2024, 8, 18, 22, 0),
        "expected_end_timestamp": datetime(2024, 8, 19, 22, 0),
        "excepted_errors": None,
    },
    {
        "path": "xml_resources/price_document_de_2026-03-05.xml",
        "params": dict(
            start_date=datetime(2026, 3, 4, 22),
            end_date=datetime(2026, 3, 5, 22),
            document_type=DocumentType.PRICE_DOCUMENT,
            process_type=ProcessType.REALISED,
            in_domain=DomainType.DE_LU,
        ),
        "expected_rows": {"PRICE_SEQUENCE_1": 92, "PRICE_SEQUENCE_2": 95},
        "expected_columns": ["PRICE_SEQUENCE_1", "PRICE_SEQUENCE_2"],
        "expected_start_timestamp": datetime(2026, 3, 4, 23, 0),
        "expected_end_timestamp": datetime(2026, 3, 5, 23, 0),
        "excepted_errors": None,
    },
    {
        "path": "xml_resources/price_document_pl_2017-03-(1-2).xml",
        "params": dict(
            start_date=datetime(2026, 3, 4, 22),
            end_date=datetime(2026, 3, 5, 22),
            document_type=DocumentType.PRICE_DOCUMENT,
            process_type=ProcessType.REALISED,
            in_domain=DomainType.PL,
        ),
    },
]
